const twitchChannels = [
	{
		channel: 'Ibai',
		follow: true,
		online: true,
		game: 'Just Chatting',
		viewers: 9783,
	},
	{
		channel: 'AuronPlay',
		follow: true,
		online: true,
		game: 'Minecraft',
		viewers: 3406,
	},
	{
		channel: 'Rubius',
		follow: true,
		online: false,
		game: 'GTA V',
		viewers: 0,
	},
	{
		channel: 'ElMariana',
		follow: false,
		online: true,
		game: 'Valorant',
		viewers: 2348,
	},
	{
		channel: 'JuanSGuarnizo',
		follow: true,
		online: false,
		game: 'Fortnite',
		viewers: 0,
	},
	{
		channel: 'ElXokas',
		follow: false,
		online: true,
		game: 'League of Legends',
		viewers: 4945,
	},
	{
		channel: 'Willyrex',
		follow: true,
		online: false,
		game: 'Call of Duty: Warzone',
		viewers: 0,
	},
	{
		channel: 'Vegetta777',
		follow: false,
		online: true,
		game: 'Minecraft',
		viewers: 2378,
	},
	{
		channel: 'Reven',
		follow: true,
		online: false,
		game: 'Apex Legends',
		viewers: 0,
	},
	{
		channel: 'Luzu',
		follow: true,
		online: true,
		game: 'FIFA 23',
		viewers: 3489,
	},
	{
		channel: 'Knekro',
		follow: true,
		online: false,
		game: 'Hearthstone',
		viewers: 0,
	},
	{
		channel: 'Staxx',
		follow: false,
		online: true,
		game: 'Among Us',
		viewers: 1560,
	},
	{
		channel: 'Alexelcapo',
		follow: true,
		online: true,
		game: 'Dark Souls',
		viewers: 1678,
	},
	{
		channel: 'BarcaGamer',
		follow: false,
		online: false,
		game: 'Rocket League',
		viewers: 0,
	},
	{
		channel: 'IlloJuan',
		follow: true,
		online: true,
		game: 'Counter-Strike: Global Offensive',
		viewers: 3645,
	},
	{
		channel: 'Grefg',
		follow: true,
		online: false,
		game: 'Fortnite',
		viewers: 0,
	},
	{
		channel: 'Cristinini',
		follow: false,
		online: true,
		game: 'Just Chatting',
		viewers: 7235,
	},
	{
		channel: 'Gemita',
		follow: true,
		online: false,
		game: 'Valorant',
		viewers: 0,
	},
	{
		channel: 'Chocas',
		follow: false,
		online: true,
		game: 'Among Us',
		viewers: 2310,
	},
	{
		channel: 'Zeling',
		follow: true,
		online: false,
		game: 'League of Legends',
		viewers: 0,
	},
];

export default twitchChannels;
