const games = [
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/512953_IGDB-285x380.jpg',
		title: 'Elden Ring',
		views: '100k',
		tags: ['RPG', 'Open World', 'Adventure'],
		isnew: true,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/21779_IGDB-285x380.jpg',
		title: 'League of Legends',
		views: '200k',
		tags: ['MOBA', 'Strategy', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/33214_IGDB-285x380.jpg',
		title: 'Fortnite',
		views: '150k',
		tags: ['Battle Royale', 'Shooter', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/32399_IGDB-285x380.jpg',
		title: 'Minecraft',
		views: '120k',
		tags: ['Sandbox', 'Survival', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/511224_IGDB-285x380.jpg',
		title: 'Apex Legends',
		views: '130k',
		tags: ['Battle Royale', 'Shooter', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/29595_IGDB-285x380.jpg',
		title: 'Dota 2',
		views: '80k',
		tags: ['MOBA', 'Strategy', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/18122_IGDB-285x380.jpg',
		title: 'World of Warcraft',
		views: '75k',
		tags: ['MMORPG', 'Fantasy', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/493057_IGDB-285x380.jpg',
		title: 'VALORANT',
		views: '160k',
		tags: ['FPS', 'Shooter', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/32982_IGDB-285x380.jpg',
		title: 'Counter-Strike: Global Offensive',
		views: '140k',
		tags: ['FPS', 'Shooter', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/21782_IGDB-285x380.jpg',
		title: 'Hearthstone',
		views: '50k',
		tags: ['Card Game', 'Strategy', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/460630_IGDB-285x380.jpg',
		title: "Tom Clancy's Rainbow Six Siege",
		views: '90k',
		tags: ['FPS', 'Shooter', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/497057-285x380.jpg',
		title: 'Destiny 2',
		views: '300k',
		tags: ['IRL', 'Chatting', 'Community'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/490100_IGDB-285x380.jpg',
		title: 'Among Us',
		views: '70k',
		tags: ['Party', 'Strategy', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/138585_IGDB-285x380.jpg',
		title: 'Hades',
		views: '30k',
		tags: ['Rogue-like', 'Action', 'Singleplayer'],
		isnew: true,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/511399_IGDB-285x380.jpg',
		title: 'Genshin Impact',
		views: '110k',
		tags: ['RPG', 'Adventure', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/23020_IGDB-285x380.jpg',
		title: 'Roblox',
		views: '60k',
		tags: ['Horror', 'Survival', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/512710_IGDB-285x380.jpg',
		title: 'Call of Duty: Warzone',
		views: '180k',
		tags: ['Battle Royale', 'Shooter', 'Multiplayer'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/516575-285x380.jpg',
		title: 'Valorant',
		views: '100k',
		tags: ['FPS', 'Shooter', 'Multiplayer'],
		isnew: true,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/27471_IGDB-285x380.jpg',
		title: 'Minecraft',
		views: '413k',
		tags: ['MMORPG', 'PvE'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/33214-285x380.jpg',
		title: 'Fortnite',
		views: '753k',
		tags: ['Shooter', 'FPS'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/21779-285x380.jpg',
		title: 'League of Legends',
		views: '966k',
		tags: ['Platformer', 'Side-scrolling'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/511224-285x380.jpg',
		title: 'Apex Legends',
		views: '112k',
		tags: ['Survival', 'Horror'],
		isnew: false,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/512710-285x380.jpg',
		title: 'Call of Duty',
		views: '980k',
		tags: ['Shooter', 'FPS'],
		isnew: true,
	},
	{
		img: 'https://static-cdn.jtvnw.net/ttv-boxart/515025-285x380.jpg',
		title: 'Overwatch',
		views: '848k',
		tags: ['Platformer', 'Side-scrolling'],
		isnew: false,
	},
];

export default games;
